'use strict';
const $ = id => document.getElementById(id);
const SIZE = 96, COUNT = SIZE * SIZE, KEY = 'pokepaint151-v1';
const COLOURS = ['#ffffff','#e3e5e8','#a4aab6','#555969','#252b38','#15151c','#fae9ce','#c7b695','#f8d030','#ffe890','#e2ad24','#c88129','#f79b41','#eb6d35','#e8413e','#a93038','#efaaaa','#f181af','#da56a0','#ad4685','#c4aff0','#9973bf','#75549c','#514b81','#91d8ec','#58aade','#3670b4','#324d85','#91d7c8','#50b7ad','#298a86','#25625f','#acd782','#6bab55','#3b8144','#256141','#d7bb95','#b48b69','#8c644a','#604737','#f6d494','#eabc6a','#c5964b','#986c36','#e3d4c2','#b5a79f','#807c7c','#575259'];
const DEFAULT = () => ({streak:0,best:0,played:0,total:0,deck:[],cursor:0,round:null});
let state=DEFAULT(),storageOK=true;
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.deck)&&s.deck.every(id=>Number.isInteger(id)&&id>=1&&id<=151)&&['streak','best','played','total','cursor'].every(k=>Number.isFinite(s[k])&&s[k]>=0)&&s.cursor<=s.deck.length)state={...DEFAULT(),...s};}catch{storageOK=false;}
let current,original,regions,mask,line,paint=new Int32Array(COUNT).fill(-1),history=[],future=[],selected='#f8d030',tool='bucket',drawing=false,lastPoint=null,ready=false,submitted=false,installEvent=null;
const ctx=$('painting').getContext('2d',{willReadFrequently:true});
function save(){try{state.round={id:current?.id,paint:Array.from(paint),result:state.round?.result??null};localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}if(!storageOK)$('saveNote').textContent='Progress can’t be saved in this browser';}
function updateStats(){for(const k of ['streak','best','played'])$(k).textContent=state[k];$('average').textContent=state.played?Math.round(state.total/state.played)+'%':'—';}
function shuffle(){const a=POKEMON.map(p=>p.id);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}if(a[0]===current?.id)[a[0],a[1]]=[a[1],a[0]];return a;}
function rgbHex(hex){return parseInt(hex.slice(1),16);}
function channels(v){return [v>>16&255,v>>8&255,v&255];}
function lab(r,g,b){const lin=v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;};r=lin(r);g=lin(g);b=lin(b);const l=Math.cbrt(.4122214708*r+.5363325363*g+.0514459929*b),m=Math.cbrt(.2119034982*r+.6806995451*g+.1073969566*b),s=Math.cbrt(.0883024619*r+.2817188376*g+.6299787005*b);return [.2104542553*l+.793617785*m-.0040720468*s,1.9779984951*l-2.428592205*m+.4505937099*s,.0259040371*l+.7827717662*m-.808675766*s];}
function distance(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);}
function colourCredit(a,b){const d=distance(a,b);return Math.max(0,Math.min(1,1-(d-.055)/.30));}
// Segment the original pixel colours once. Nearby shading colours share a section.
function analyse(data){mask=new Uint8Array(COUNT);line=new Uint8Array(COUNT);regions=new Int16Array(COUNT).fill(-1);const colours=new Map();
for(let p=0;p<COUNT;p++){const i=p*4;if(data[i+3]<128)continue;const rgb=[data[i],data[i+1],data[i+2]];if(Math.max(...rgb)<78){line[p]=1;continue;}mask[p]=1;const key=(rgb[0]<<16)|(rgb[1]<<8)|rgb[2];if(!colours.has(key))colours.set(key,{key,lab:lab(...rgb),count:0});colours.get(key).count++;}
const groups=[];const assignments=new Map();for(const c of [...colours.values()].sort((a,b)=>b.count-a.count)){let best=-1,dist=Infinity;for(let j=0;j<groups.length;j++){const a=c.lab,b=groups[j];const d=Math.hypot((a[0]-b[0])*.45,a[1]-b[1],a[2]-b[2]);if(d<dist){dist=d;best=j;}}if(dist>.079){best=groups.length;groups.push(c.lab);}assignments.set(c.key,best);}
for(let p=0;p<COUNT;p++)if(mask[p]){const i=p*4;regions[p]=assignments.get((data[i]<<16)|(data[i+1]<<8)|data[i+2]);}}
function renderTo(context,values){const out=context.createImageData(SIZE,SIZE);for(let p=0;p<COUNT;p++){const i=p*4;if(line[p]){out.data.set([32,36,44,255],i);continue;}if(!mask[p])continue;let rgb=values[p]<0?[255,255,255]:channels(values[p]);if(values[p]<0){const x=p%SIZE,y=Math.floor(p/SIZE);const boundary=(x>0&&mask[p-1]&&regions[p-1]!==regions[p])||(y>0&&mask[p-SIZE]&&regions[p-SIZE]!==regions[p]);if(boundary)rgb=[193,199,204];}out.data.set([...rgb,255],i);}context.putImageData(out,0,0);}
function render(){renderTo(ctx,paint);let filled=0,total=0;for(let i=0;i<COUNT;i++)if(mask[i]){total++;if(paint[i]>=0)filled++;}$('coverage').textContent=Math.round(100*filled/Math.max(1,total))+'% painted';$('grade').disabled=!ready||submitted||filled===0;$('undo').disabled=!history.length||submitted;$('redo').disabled=!future.length||submitted;}
function snapshot(){history.push(paint.slice());if(history.length>25)history.shift();future=[];}
function selectColour(colour){selected=colour.toLowerCase();$('customColour').value=selected;$('selectedChip').style.background=selected;$('colourHex').textContent=selected.toUpperCase();document.querySelectorAll('.swatch').forEach(b=>{const active=b.dataset.colour===selected;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active);});}
function selectTool(t){tool=t;for(const k of ['bucket','brush']){$(k).classList.toggle('active',t===k);$(k).setAttribute('aria-pressed',t===k);}$('brushOptions').hidden=t!=='brush';$('hint').textContent=t==='bucket'?'Choose a colour, then tap a section to fill it.':'Drag to paint. The brush stays inside the Pokémon.';}
function fill(x,y){const p=y*SIZE+x;if(!mask[p])return false;const target=regions[p],seen=new Uint8Array(COUNT),stack=[p],value=rgbHex(selected);while(stack.length){const i=stack.pop();if(seen[i]||!mask[i]||regions[i]!==target)continue;seen[i]=1;paint[i]=value;const cx=i%SIZE,cy=Math.floor(i/SIZE);if(cx>0)stack.push(i-1);if(cx<SIZE-1)stack.push(i+1);if(cy>0)stack.push(i-SIZE);if(cy<SIZE-1)stack.push(i+SIZE);}return true;}
function dab(x,y){const r=+$('brushSize').value,v=rgbHex(selected);for(let yy=Math.max(0,y-r);yy<=Math.min(SIZE-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(SIZE-1,x+r);xx++)if((xx-x)**2+(yy-y)**2<=r*r&&mask[yy*SIZE+xx])paint[yy*SIZE+xx]=v;}
function stroke(a,b){const n=Math.max(Math.abs(b.x-a.x),Math.abs(b.y-a.y),1);for(let i=0;i<=n;i++)dab(Math.round(a.x+(b.x-a.x)*i/n),Math.round(a.y+(b.y-a.y)*i/n));}
function point(e){const r=$('painting').getBoundingClientRect();return{x:Math.max(0,Math.min(SIZE-1,Math.floor((e.clientX-r.left)/r.width*SIZE))),y:Math.max(0,Math.min(SIZE-1,Math.floor((e.clientY-r.top)/r.height*SIZE)))};}
$('painting').addEventListener('pointerdown',e=>{if(!ready||submitted||e.isPrimary===false||(e.pointerType==='mouse'&&e.button!==0))return;e.preventDefault();const p=point(e);if(!mask[p.y*SIZE+p.x]&&tool==='bucket')return;snapshot();if(tool==='bucket'){fill(p.x,p.y);render();save();}else{drawing=true;lastPoint=p;$('painting').setPointerCapture(e.pointerId);dab(p.x,p.y);render();}});
$('painting').addEventListener('pointermove',e=>{if(!drawing||e.isPrimary===false)return;const p=point(e);stroke(lastPoint,p);lastPoint=p;render();});
function finishStroke(){if(drawing){drawing=false;lastPoint=null;save();}}for(const type of ['pointerup','pointercancel','lostpointercapture'])$('painting').addEventListener(type,finishStroke);
$('undo').onclick=()=>{if(submitted||!history.length)return;future.push(paint.slice());paint=history.pop();render();save();};$('redo').onclick=()=>{if(submitted||!future.length)return;history.push(paint.slice());paint=future.pop();render();save();};
let confirmAction=null;function confirm(title,text,label,action){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('acceptConfirm').textContent=label;confirmAction=action;$('confirmDialog').showModal();}$('cancelConfirm').onclick=()=>$('confirmDialog').close();$('acceptConfirm').onclick=()=>{$('confirmDialog').close();confirmAction?.();confirmAction=null;};
$('clear').onclick=()=>{if(!ready||submitted)return;confirm('Clear your painting?','You can undo this after clearing.','Clear painting',()=>{snapshot();paint.fill(-1);render();save();});};
$('skip').onclick=()=>{if(!ready||submitted)return;confirm('Skip this Pokémon?','Your current A streak will return to zero. Your best streak stays saved.','Skip Pokémon',()=>{state.streak=0;updateStats();advance();});};
function scorePainting(){let sum=0,total=0;const cache=new Map();for(let p=0;p<COUNT;p++)if(mask[p]){total++;if(paint[p]<0)continue;const i=p*4,orig=(original[i]<<16)|(original[i+1]<<8)|original[i+2],key=orig+':'+paint[p];if(!cache.has(key))cache.set(key,colourCredit(lab(...channels(orig)),lab(...channels(paint[p]))));sum+=cache.get(key);}return Math.round(100*sum/Math.max(total,1));}
function letter(score){return score>=95?'A+':score>=80?'A':score>=65?'B':score>=50?'C':score>=35?'D':'F';}
function showResult(result){$('gradeLetter').textContent=letter(result.score);$('score').textContent=result.score;$('resultTitle').textContent=result.score>=95?'Picture perfect!':result.score>=80?'You know your colours!':result.score>=65?'Pretty close!':'Keep practising!';$('resultMessage').textContent=result.score>=80?'Another A for your collection.':`${80-result.score} more percentage points for an A.`;$('streakMessage').textContent=result.score>=80?`${state.streak} in a row · Best streak: ${state.best}`:'A streak reset. A fresh run starts next round.';renderTo($('yourResult').getContext('2d'),paint);$('originalResult').getContext('2d').putImageData(new ImageData(original,SIZE,SIZE),0,0);if(!$('resultDialog').open)$('resultDialog').showModal();}
$('grade').onclick=()=>{if(!ready||submitted||!paint.some(v=>v>=0))return;finishStroke();submitted=true;const score=scorePainting();state.played++;state.total+=score;state.streak=score>=80?state.streak+1:0;state.best=Math.max(state.best,state.streak);state.round.result={score};save();updateStats();render();showResult(state.round.result);};
$('resultDialog').addEventListener('cancel',e=>e.preventDefault());$('next').onclick=()=>{$('resultDialog').close();advance();};
function advance(){state.cursor++;if(state.cursor>=state.deck.length){state.deck=shuffle();state.cursor=0;}state.round=null;paint.fill(-1);current=POKEMON.find(p=>p.id===state.deck[state.cursor]);save();loadRound();}
async function loadRound(){ready=false;submitted=false;drawing=false;history=[];future=[];$('grade').disabled=true;$('loadError').hidden=true;$('painting').hidden=false;ctx.clearRect(0,0,SIZE,SIZE);if(!state.deck.length){state.deck=shuffle();state.cursor=0;}current=POKEMON.find(p=>p.id===state.deck[state.cursor]);$('pokemonName').textContent=current.name;$('number').textContent='KANTO / '+String(current.id).padStart(3,'0');$('roundLabel').textContent='ROUND '+(state.played+1);const img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=`assets/${current.id}.png`;});const temp=document.createElement('canvas');temp.width=SIZE;temp.height=SIZE;const tc=temp.getContext('2d',{willReadFrequently:true});tc.drawImage(img,0,0);const raw=tc.getImageData(0,0,SIZE,SIZE).data;let minX=SIZE,minY=SIZE,maxX=0,maxY=0;for(let p=0;p<COUNT;p++)if(raw[p*4+3]>127){minX=Math.min(minX,p%SIZE);maxX=Math.max(maxX,p%SIZE);minY=Math.min(minY,Math.floor(p/SIZE));maxY=Math.max(maxY,Math.floor(p/SIZE));}const w=maxX-minX+1,h=maxY-minY+1,scale=76/Math.max(w,h),dw=Math.round(w*scale),dh=Math.round(h*scale);tc.clearRect(0,0,SIZE,SIZE);tc.imageSmoothingEnabled=false;tc.drawImage(img,minX,minY,w,h,Math.floor((SIZE-dw)/2),Math.floor((SIZE-dh)/2),dw,dh);original=tc.getImageData(0,0,SIZE,SIZE).data;analyse(original);const saved=state.round;paint=saved?.id===current.id&&Array.isArray(saved.paint)&&saved.paint.length===COUNT&&saved.paint.every(v=>Number.isInteger(v)&&v>=-1&&v<=0xffffff)?Int32Array.from(saved.paint):new Int32Array(COUNT).fill(-1);submitted=Boolean(saved?.id===current.id&&saved.result&&Number.isFinite(saved.result.score));ready=true;save();render();if(submitted)showResult(state.round.result);}catch{$('painting').hidden=true;$('loadError').hidden=false;$('hint').textContent='Check your connection and try again.';}}
$('retry').onclick=loadRound;
for(const colour of COLOURS){const b=document.createElement('button');b.className='swatch';b.style.background=colour;b.dataset.colour=colour;b.title=colour.toUpperCase();b.setAttribute('aria-label','Paint '+colour.toUpperCase());b.setAttribute('aria-pressed','false');b.onclick=()=>selectColour(colour);$('palette').append(b);}
$('customColour').oninput=e=>selectColour(e.target.value);$('bucket').onclick=()=>selectTool('bucket');$('brush').onclick=()=>selectTool('brush');$('brushSize').oninput=e=>$('brushValue').textContent=e.target.value;
$('settings').onclick=()=>$('settingsDialog').showModal();$('closeSettings').onclick=()=>$('settingsDialog').close();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('install').textContent='Install PokéPaint';});$('install').onclick=async()=>{if(installEvent){await installEvent.prompt();await installEvent.userChoice;installEvent=null;}else{$('installHelp').textContent=matchMedia('(display-mode: standalone)').matches?'PokéPaint is already installed.':'Use your browser menu to install. On iPhone or iPad: Safari → Share → Add to Home Screen. If you opened this in another app, open it in your main browser first.';}};
window.addEventListener('appinstalled',()=>{$('install').textContent='Installed';$('install').disabled=true;});
window.addEventListener('pagehide',()=>{if(ready)save();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready)save();});
if('serviceWorker' in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('sw.js').then(async()=>{await navigator.serviceWorker.ready;$('offlineStatus').textContent='Ready for offline play. All 151 Pokémon are saved.';}).catch(()=>{$('offlineStatus').textContent='Offline setup didn’t finish. Keep this page open online and try again later.';});}else $('offlineStatus').textContent='Install and offline play require HTTPS hosting, such as GitHub Pages.';
selectColour(selected);updateStats();loadRound();
// Optional agent controls use the same public actions as the on-screen tools.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_paint_tool',description:'Choose a paint colour and select bucket fill or brush without painting or submitting.',inputSchema:{type:'object',properties:{colour:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},tool:{type:'string',enum:['bucket','brush']}},required:['colour','tool'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!/^#[0-9a-fA-F]{6}$/.test(input.colour)||!['bucket','brush'].includes(input.tool))throw new Error('Choose a six-digit hex colour and bucket or brush.');selectColour(input.colour);selectTool(input.tool);return{colour:selected,tool};}})).catch(()=>{});}catch{}}
